// This file is automatically @generated by Asphalt.
// It is not intended for manual editing.
declare const animations: {
    "meditation.rbxm": string;
    "pushup.rbxm": string;
};

export = animations;
